# Ick note - This file is for running in docker compose with preb
version: "3.9"

networks:
  frontend:
  backend:

services:
  redis:
    image: redis:latest
    networks:
      - frontend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend

  vote:
    image: vinaykumar1999/voting-app
    ports:
      - "6000:80"   # host:container (changed from 5000 → 6000)
    networks:
      - frontend

  result:
    image: vinaykumar1999/result-app
    ports:
      - "6001:80"   # host:container (changed from 5001 → 6001)
    networks:
      - backend

  worker:
    image: vinaykumar1999/worker-app
    depends_on:
      - redis
      - db
    networks:
      - frontend
      - backend

